# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Tue Sep 23 20:15:23 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(953, 670)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(808, 670))
        MainWindow.setMaximumSize(QtCore.QSize(2000, 2000))
        MainWindow.setSizeIncrement(QtCore.QSize(1, 1))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/antialias_Icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSpacing(-1)
        self.verticalLayout_4.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.graphicsView = GridGraphicsView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setMinimumSize(QtCore.QSize(550, 550))
        self.graphicsView.setSizeIncrement(QtCore.QSize(1, 1))
        self.graphicsView.setProperty("cursor", QtCore.Qt.PointingHandCursor)
        self.graphicsView.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.graphicsView.setAcceptDrops(False)
        self.graphicsView.setStatusTip("")
        self.graphicsView.setAutoFillBackground(False)
        self.graphicsView.setFrameShape(QtGui.QFrame.StyledPanel)
        self.graphicsView.setFrameShadow(QtGui.QFrame.Sunken)
        self.graphicsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.graphicsView.setAlignment(QtCore.Qt.AlignCenter)
        self.graphicsView.setDragMode(QtGui.QGraphicsView.RubberBandDrag)
        self.graphicsView.setCacheMode(QtGui.QGraphicsView.CacheNone)
        self.graphicsView.setRubberBandSelectionMode(QtCore.Qt.IntersectsItemShape)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_4.addWidget(self.graphicsView)
        self.frameSlider = QtGui.QSlider(self.centralwidget)
        self.frameSlider.setMinimumSize(QtCore.QSize(550, 0))
        self.frameSlider.setCursor(QtCore.Qt.PointingHandCursor)
        self.frameSlider.setMinimum(0)
        self.frameSlider.setMaximum(0)
        self.frameSlider.setOrientation(QtCore.Qt.Horizontal)
        self.frameSlider.setInvertedAppearance(False)
        self.frameSlider.setInvertedControls(False)
        self.frameSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.frameSlider.setTickInterval(1)
        self.frameSlider.setObjectName("frameSlider")
        self.verticalLayout_4.addWidget(self.frameSlider)
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_4.addWidget(self.progressBar)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setEnabled(True)
        self.toolBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolBar.setMovable(True)
        self.toolBar.setAllowedAreas(QtCore.Qt.AllToolBarAreas)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 953, 20))
        self.menuBar.setDefaultUp(False)
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuFrames = QtGui.QMenu(self.menuBar)
        self.menuFrames.setTearOffEnabled(False)
        self.menuFrames.setSeparatorsCollapsible(False)
        self.menuFrames.setObjectName("menuFrames")
        self.menuGo_to = QtGui.QMenu(self.menuFrames)
        self.menuGo_to.setObjectName("menuGo_to")
        self.menuNew = QtGui.QMenu(self.menuFrames)
        self.menuNew.setObjectName("menuNew")
        self.menuSelection = QtGui.QMenu(self.menuBar)
        self.menuSelection.setTearOffEnabled(True)
        self.menuSelection.setSeparatorsCollapsible(False)
        self.menuSelection.setObjectName("menuSelection")
        self.menuShift = QtGui.QMenu(self.menuSelection)
        self.menuShift.setObjectName("menuShift")
        self.menuEdit = QtGui.QMenu(self.menuBar)
        self.menuEdit.setEnabled(False)
        self.menuEdit.setTearOffEnabled(False)
        self.menuEdit.setSeparatorsCollapsible(False)
        self.menuEdit.setObjectName("menuEdit")
        self.menuColoring = QtGui.QMenu(self.menuBar)
        self.menuColoring.setObjectName("menuColoring")
        self.menuPlayer = QtGui.QMenu(self.menuBar)
        self.menuPlayer.setObjectName("menuPlayer")
        self.menuGenerate = QtGui.QMenu(self.menuBar)
        self.menuGenerate.setObjectName("menuGenerate")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.dockWidget = QtGui.QDockWidget(MainWindow)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.dockWidget.setFont(font)
        self.dockWidget.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dockWidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout_2 = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.colorBox = QtGui.QGroupBox(self.dockWidgetContents)
        self.colorBox.setObjectName("colorBox")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.colorBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.colorButton = QtGui.QPushButton(self.colorBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorButton.sizePolicy().hasHeightForWidth())
        self.colorButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.colorButton.setFont(font)
        self.colorButton.setAutoFillBackground(False)
        self.colorButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/gnome-applications-graphics.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.colorButton.setIcon(icon1)
        self.colorButton.setAutoDefault(False)
        self.colorButton.setDefault(False)
        self.colorButton.setFlat(False)
        self.colorButton.setObjectName("colorButton")
        self.verticalLayout_2.addWidget(self.colorButton)
        self.tintButton = QtGui.QPushButton(self.colorBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tintButton.sizePolicy().hasHeightForWidth())
        self.tintButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.tintButton.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/fill-color.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tintButton.setIcon(icon2)
        self.tintButton.setFlat(False)
        self.tintButton.setObjectName("tintButton")
        self.verticalLayout_2.addWidget(self.tintButton)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addWidget(self.colorBox)
        self.currentFrameBox = QtGui.QGroupBox(self.dockWidgetContents)
        self.currentFrameBox.setObjectName("currentFrameBox")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.currentFrameBox)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtGui.QLabel(self.currentFrameBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.durationSpinBox = QtGui.QSpinBox(self.currentFrameBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.durationSpinBox.sizePolicy().hasHeightForWidth())
        self.durationSpinBox.setSizePolicy(sizePolicy)
        self.durationSpinBox.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.durationSpinBox.setFont(font)
        self.durationSpinBox.setMaximum(99999)
        self.durationSpinBox.setSingleStep(10)
        self.durationSpinBox.setProperty("value", 100)
        self.durationSpinBox.setObjectName("durationSpinBox")
        self.verticalLayout.addWidget(self.durationSpinBox)
        self.verticalLayout_9.addLayout(self.verticalLayout)
        self.verticalLayout_3.addWidget(self.currentFrameBox)
        self.playerBox = QtGui.QGroupBox(self.dockWidgetContents)
        self.playerBox.setObjectName("playerBox")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.playerBox)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.loopCheckbox = QtGui.QCheckBox(self.playerBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setBold(False)
        self.loopCheckbox.setFont(font)
        self.loopCheckbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.loopCheckbox.setAutoFillBackground(False)
        self.loopCheckbox.setTristate(False)
        self.loopCheckbox.setObjectName("loopCheckbox")
        self.verticalLayout_6.addWidget(self.loopCheckbox)
        self.playButton = QtGui.QToolButton(self.playerBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playButton.sizePolicy().hasHeightForWidth())
        self.playButton.setSizePolicy(sizePolicy)
        self.playButton.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.playButton.setFont(font)
        self.playButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.playButton.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.playButton.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        self.playButton.setAutoRaise(False)
        self.playButton.setArrowType(QtCore.Qt.NoArrow)
        self.playButton.setObjectName("playButton")
        self.verticalLayout_6.addWidget(self.playButton)
        self.playOnDeviceButton = QtGui.QToolButton(self.playerBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playOnDeviceButton.sizePolicy().hasHeightForWidth())
        self.playOnDeviceButton.setSizePolicy(sizePolicy)
        self.playOnDeviceButton.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.playOnDeviceButton.setFont(font)
        self.playOnDeviceButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.playOnDeviceButton.setAutoRaise(False)
        self.playOnDeviceButton.setObjectName("playOnDeviceButton")
        self.verticalLayout_6.addWidget(self.playOnDeviceButton)
        self.verticalLayout_10.addLayout(self.verticalLayout_6)
        self.verticalLayout_3.addWidget(self.playerBox)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.infoBox = QtGui.QGroupBox(self.dockWidgetContents)
        self.infoBox.setObjectName("infoBox")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.infoBox)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.metaInfoTable = QtGui.QTableWidget(self.infoBox)
        self.metaInfoTable.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.metaInfoTable.setFont(font)
        self.metaInfoTable.setFrameShape(QtGui.QFrame.StyledPanel)
        self.metaInfoTable.setFrameShadow(QtGui.QFrame.Sunken)
        self.metaInfoTable.setMidLineWidth(1)
        self.metaInfoTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.metaInfoTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.metaInfoTable.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.metaInfoTable.setGridStyle(QtCore.Qt.SolidLine)
        self.metaInfoTable.setColumnCount(2)
        self.metaInfoTable.setObjectName("metaInfoTable")
        self.metaInfoTable.setColumnCount(2)
        self.metaInfoTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.metaInfoTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.metaInfoTable.setHorizontalHeaderItem(1, item)
        self.metaInfoTable.horizontalHeader().setMinimumSectionSize(20)
        self.metaInfoTable.horizontalHeader().setStretchLastSection(True)
        self.metaInfoTable.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_7.addWidget(self.metaInfoTable)
        self.verticalLayout_11.addLayout(self.verticalLayout_7)
        self.gridLayout_2.addWidget(self.infoBox, 1, 0, 1, 1)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget)
        self.actionCreate_new_frame = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/list-add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCreate_new_frame.setIcon(icon3)
        self.actionCreate_new_frame.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionCreate_new_frame.setObjectName("actionCreate_new_frame")
        self.actionExit = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/System-log-out-2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon4)
        self.actionExit.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionExit.setObjectName("actionExit")
        self.actionLoad_BLM = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/document-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLoad_BLM.setIcon(icon5)
        self.actionLoad_BLM.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionLoad_BLM.setAutoRepeat(False)
        self.actionLoad_BLM.setObjectName("actionLoad_BLM")
        self.actionDuplicate_frame = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/edit-copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDuplicate_frame.setIcon(icon6)
        self.actionDuplicate_frame.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionDuplicate_frame.setObjectName("actionDuplicate_frame")
        self.actionPlayStop = QtGui.QAction(MainWindow)
        self.actionPlayStop.setEnabled(False)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/media-playback-start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPlayStop.setIcon(icon7)
        self.actionPlayStop.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionPlayStop.setAutoRepeat(False)
        self.actionPlayStop.setObjectName("actionPlayStop")
        self.actionNew = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/document-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon8)
        self.actionNew.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionNew.setAutoRepeat(False)
        self.actionNew.setObjectName("actionNew")
        self.actionSave_as = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/document-save-as.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_as.setIcon(icon9)
        self.actionSave_as.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionSave_as.setAutoRepeat(False)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionGo_to_previous_frame = QtGui.QAction(MainWindow)
        self.actionGo_to_previous_frame.setEnabled(False)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/go-previous.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGo_to_previous_frame.setIcon(icon10)
        self.actionGo_to_previous_frame.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionGo_to_previous_frame.setObjectName("actionGo_to_previous_frame")
        self.actionGo_to_next_frame = QtGui.QAction(MainWindow)
        self.actionGo_to_next_frame.setEnabled(False)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/go-next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGo_to_next_frame.setIcon(icon11)
        self.actionGo_to_next_frame.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionGo_to_next_frame.setObjectName("actionGo_to_next_frame")
        self.actionSelect_all = QtGui.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/view-grid-all.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSelect_all.setIcon(icon12)
        self.actionSelect_all.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionSelect_all.setObjectName("actionSelect_all")
        self.actionDeselect_all = QtGui.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icons/view-grid.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDeselect_all.setIcon(icon13)
        self.actionDeselect_all.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionDeselect_all.setObjectName("actionDeselect_all")
        self.actionInvert_selection = QtGui.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icons/document-encrypted.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInvert_selection.setIcon(icon14)
        self.actionInvert_selection.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionInvert_selection.setObjectName("actionInvert_selection")
        self.actionSelect_by_color = QtGui.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/icons/color.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSelect_by_color.setIcon(icon15)
        self.actionSelect_by_color.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionSelect_by_color.setObjectName("actionSelect_by_color")
        self.actionUndo = QtGui.QAction(MainWindow)
        self.actionUndo.setEnabled(True)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/icons/edit-undo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUndo.setIcon(icon16)
        self.actionUndo.setObjectName("actionUndo")
        self.actionChoose_color = QtGui.QAction(MainWindow)
        self.actionChoose_color.setIcon(icon1)
        self.actionChoose_color.setObjectName("actionChoose_color")
        self.actionTint_selected_tiles = QtGui.QAction(MainWindow)
        self.actionTint_selected_tiles.setIcon(icon2)
        self.actionTint_selected_tiles.setObjectName("actionTint_selected_tiles")
        self.actionShift_left = QtGui.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/icons/arrow-left-double.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShift_left.setIcon(icon17)
        self.actionShift_left.setObjectName("actionShift_left")
        self.actionShift_right = QtGui.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/icons/arrow-right-double.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShift_right.setIcon(icon18)
        self.actionShift_right.setObjectName("actionShift_right")
        self.actionConnect_to_device = QtGui.QAction(MainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/icons/network-wired.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConnect_to_device.setIcon(icon19)
        self.actionConnect_to_device.setObjectName("actionConnect_to_device")
        self.actionPlayStopDevice = QtGui.QAction(MainWindow)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/icons/media-flash.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPlayStopDevice.setIcon(icon20)
        self.actionPlayStopDevice.setObjectName("actionPlayStopDevice")
        self.actionRandomize_selected_tiles = QtGui.QAction(MainWindow)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/icons/dice.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRandomize_selected_tiles.setIcon(icon21)
        self.actionRandomize_selected_tiles.setObjectName("actionRandomize_selected_tiles")
        self.actionShift_content_up = QtGui.QAction(MainWindow)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/icons/arrow-up-double.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShift_content_up.setIcon(icon22)
        self.actionShift_content_up.setObjectName("actionShift_content_up")
        self.actionShift_content_down = QtGui.QAction(MainWindow)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/icons/arrow-down-double.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShift_content_down.setIcon(icon23)
        self.actionShift_content_down.setObjectName("actionShift_content_down")
        self.actionCopy_Selection = QtGui.QAction(MainWindow)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(":/icons/edit-copy-selection.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCopy_Selection.setIcon(icon24)
        self.actionCopy_Selection.setObjectName("actionCopy_Selection")
        self.actionPaste = QtGui.QAction(MainWindow)
        self.actionPaste.setEnabled(False)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(":/icons/edit-paste.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPaste.setIcon(icon25)
        self.actionPaste.setObjectName("actionPaste")
        self.actionPersist_changes = QtGui.QAction(MainWindow)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(":/icons/text-x-generic_with_pencil.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPersist_changes.setIcon(icon26)
        self.actionPersist_changes.setObjectName("actionPersist_changes")
        self.actionCut_Selection = QtGui.QAction(MainWindow)
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(":/icons/edit-cut.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCut_Selection.setIcon(icon27)
        self.actionCut_Selection.setObjectName("actionCut_Selection")
        self.actionExport_frame = QtGui.QAction(MainWindow)
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(":/icons/document-export.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExport_frame.setIcon(icon28)
        self.actionExport_frame.setObjectName("actionExport_frame")
        self.actionGenerate_color_gradient = QtGui.QAction(MainWindow)
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap(":/icons/gradient.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGenerate_color_gradient.setIcon(icon29)
        self.actionGenerate_color_gradient.setObjectName("actionGenerate_color_gradient")
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setEnabled(False)
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap(":/icons/document-save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon30)
        self.actionSave.setObjectName("actionSave")
        self.actionGo_to_frame = QtGui.QAction(MainWindow)
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap(":/icons/go-jump.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGo_to_frame.setIcon(icon31)
        self.actionGo_to_frame.setObjectName("actionGo_to_frame")
        self.actionZoom_in = QtGui.QAction(MainWindow)
        icon32 = QtGui.QIcon()
        icon32.addPixmap(QtGui.QPixmap(":/icons/view-zoom-in.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom_in.setIcon(icon32)
        self.actionZoom_in.setObjectName("actionZoom_in")
        self.actionZoom_out = QtGui.QAction(MainWindow)
        self.actionZoom_out.setEnabled(True)
        icon33 = QtGui.QIcon()
        icon33.addPixmap(QtGui.QPixmap(":/icons/view-zoom-out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom_out.setIcon(icon33)
        self.actionZoom_out.setObjectName("actionZoom_out")
        self.actionFit_zoom = QtGui.QAction(MainWindow)
        icon34 = QtGui.QIcon()
        icon34.addPixmap(QtGui.QPixmap(":/icons/view-zoom-fit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFit_zoom.setIcon(icon34)
        self.actionFit_zoom.setObjectName("actionFit_zoom")
        self.actionGenerate_function = QtGui.QAction(MainWindow)
        icon35 = QtGui.QIcon()
        icon35.addPixmap(QtGui.QPixmap(":/icons/office-chart-line.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGenerate_function.setIcon(icon35)
        self.actionGenerate_function.setObjectName("actionGenerate_function")
        self.actionImport_from_image = QtGui.QAction(MainWindow)
        icon36 = QtGui.QIcon()
        icon36.addPixmap(QtGui.QPixmap(":/icons/document-import.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionImport_from_image.setIcon(icon36)
        self.actionImport_from_image.setObjectName("actionImport_from_image")
        self.actionRotate_right = QtGui.QAction(MainWindow)
        icon37 = QtGui.QIcon()
        icon37.addPixmap(QtGui.QPixmap(":/icons/object-rotate-right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRotate_right.setIcon(icon37)
        self.actionRotate_right.setObjectName("actionRotate_right")
        self.actionRotate_left = QtGui.QAction(MainWindow)
        icon38 = QtGui.QIcon()
        icon38.addPixmap(QtGui.QPixmap(":/icons/object-rotate-left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRotate_left.setIcon(icon38)
        self.actionRotate_left.setObjectName("actionRotate_left")
        self.actionDelete_colors = QtGui.QAction(MainWindow)
        icon39 = QtGui.QIcon()
        icon39.addPixmap(QtGui.QPixmap(":/icons/edit-delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDelete_colors.setIcon(icon39)
        self.actionDelete_colors.setObjectName("actionDelete_colors")
        self.actionExport_frames = QtGui.QAction(MainWindow)
        icon40 = QtGui.QIcon()
        icon40.addPixmap(QtGui.QPixmap(":/icons/document-export-table.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExport_frames.setIcon(icon40)
        self.actionExport_frames.setObjectName("actionExport_frames")
        self.actionDelete_frame = QtGui.QAction(MainWindow)
        icon41 = QtGui.QIcon()
        icon41.addPixmap(QtGui.QPixmap(":/icons/list-remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDelete_frame.setIcon(icon41)
        self.actionDelete_frame.setObjectName("actionDelete_frame")
        self.actionGenerate_ticker_font = QtGui.QAction(MainWindow)
        icon42 = QtGui.QIcon()
        icon42.addPixmap(QtGui.QPixmap(":/icons/application-x-font-ttf.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGenerate_ticker_font.setIcon(icon42)
        self.actionGenerate_ticker_font.setObjectName("actionGenerate_ticker_font")
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionGo_to_previous_frame)
        self.toolBar.addAction(self.actionGo_to_next_frame)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCreate_new_frame)
        self.toolBar.addAction(self.actionDuplicate_frame)
        self.toolBar.addAction(self.actionDelete_frame)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionRotate_right)
        self.toolBar.addAction(self.actionRotate_left)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionZoom_out)
        self.toolBar.addAction(self.actionZoom_in)
        self.toolBar.addAction(self.actionFit_zoom)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSelect_all)
        self.toolBar.addAction(self.actionDeselect_all)
        self.toolBar.addAction(self.actionCut_Selection)
        self.toolBar.addAction(self.actionPaste)
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionLoad_BLM)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addAction(self.actionExport_frames)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuGo_to.addAction(self.actionGo_to_previous_frame)
        self.menuGo_to.addAction(self.actionGo_to_next_frame)
        self.menuGo_to.addAction(self.actionGo_to_frame)
        self.menuNew.addAction(self.actionCreate_new_frame)
        self.menuNew.addAction(self.actionDuplicate_frame)
        self.menuNew.addAction(self.actionImport_from_image)
        self.menuFrames.addAction(self.menuNew.menuAction())
        self.menuFrames.addAction(self.actionDelete_frame)
        self.menuFrames.addSeparator()
        self.menuFrames.addAction(self.actionRotate_right)
        self.menuFrames.addAction(self.actionRotate_left)
        self.menuFrames.addSeparator()
        self.menuFrames.addAction(self.actionExport_frame)
        self.menuFrames.addSeparator()
        self.menuFrames.addAction(self.menuGo_to.menuAction())
        self.menuFrames.addAction(self.actionPersist_changes)
        self.menuShift.addAction(self.actionShift_left)
        self.menuShift.addAction(self.actionShift_right)
        self.menuShift.addAction(self.actionShift_content_up)
        self.menuShift.addAction(self.actionShift_content_down)
        self.menuSelection.addAction(self.actionSelect_all)
        self.menuSelection.addAction(self.actionDeselect_all)
        self.menuSelection.addSeparator()
        self.menuSelection.addAction(self.actionInvert_selection)
        self.menuSelection.addAction(self.actionSelect_by_color)
        self.menuSelection.addSeparator()
        self.menuSelection.addAction(self.actionDelete_colors)
        self.menuSelection.addAction(self.actionCopy_Selection)
        self.menuSelection.addAction(self.actionCut_Selection)
        self.menuSelection.addAction(self.actionPaste)
        self.menuSelection.addSeparator()
        self.menuSelection.addAction(self.menuShift.menuAction())
        self.menuEdit.addAction(self.actionUndo)
        self.menuColoring.addAction(self.actionChoose_color)
        self.menuColoring.addAction(self.actionTint_selected_tiles)
        self.menuColoring.addAction(self.actionRandomize_selected_tiles)
        self.menuPlayer.addAction(self.actionPlayStop)
        self.menuPlayer.addSeparator()
        self.menuPlayer.addAction(self.actionConnect_to_device)
        self.menuPlayer.addAction(self.actionPlayStopDevice)
        self.menuGenerate.addAction(self.actionGenerate_color_gradient)
        self.menuGenerate.addAction(self.actionGenerate_function)
        self.menuGenerate.addAction(self.actionGenerate_ticker_font)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuFrames.menuAction())
        self.menuBar.addAction(self.menuSelection.menuAction())
        self.menuBar.addAction(self.menuColoring.menuAction())
        self.menuBar.addAction(self.menuGenerate.menuAction())
        self.menuBar.addAction(self.menuPlayer.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Blink", None, QtGui.QApplication.UnicodeUTF8))
        self.graphicsView.setWhatsThis(QtGui.QApplication.translate("MainWindow", "(CTRL+) Left-click to select a tile, right-click to tint", None, QtGui.QApplication.UnicodeUTF8))
        self.progressBar.setFormat(QtGui.QApplication.translate("MainWindow", "%p% (Frame %v/%m)", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Toolbar", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFrames.setTitle(QtGui.QApplication.translate("MainWindow", "&Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.menuGo_to.setTitle(QtGui.QApplication.translate("MainWindow", "&Go to...", None, QtGui.QApplication.UnicodeUTF8))
        self.menuNew.setTitle(QtGui.QApplication.translate("MainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSelection.setTitle(QtGui.QApplication.translate("MainWindow", "&Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.menuShift.setTitle(QtGui.QApplication.translate("MainWindow", "&Shift", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "&Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuColoring.setTitle(QtGui.QApplication.translate("MainWindow", "&Coloring", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPlayer.setTitle(QtGui.QApplication.translate("MainWindow", "&Player", None, QtGui.QApplication.UnicodeUTF8))
        self.menuGenerate.setTitle(QtGui.QApplication.translate("MainWindow", "Generate", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.colorBox.setTitle(QtGui.QApplication.translate("MainWindow", "Color", None, QtGui.QApplication.UnicodeUTF8))
        self.tintButton.setText(QtGui.QApplication.translate("MainWindow", "Tint selected tiles", None, QtGui.QApplication.UnicodeUTF8))
        self.currentFrameBox.setTitle(QtGui.QApplication.translate("MainWindow", "Current Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Duration (ms)", None, QtGui.QApplication.UnicodeUTF8))
        self.playerBox.setTitle(QtGui.QApplication.translate("MainWindow", "Player", None, QtGui.QApplication.UnicodeUTF8))
        self.loopCheckbox.setText(QtGui.QApplication.translate("MainWindow", "Loop playback", None, QtGui.QApplication.UnicodeUTF8))
        self.playButton.setText(QtGui.QApplication.translate("MainWindow", "Playback", None, QtGui.QApplication.UnicodeUTF8))
        self.playOnDeviceButton.setText(QtGui.QApplication.translate("MainWindow", "Playback on Device", None, QtGui.QApplication.UnicodeUTF8))
        self.infoBox.setTitle(QtGui.QApplication.translate("MainWindow", "File information", None, QtGui.QApplication.UnicodeUTF8))
        self.metaInfoTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Property", None, QtGui.QApplication.UnicodeUTF8))
        self.metaInfoTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCreate_new_frame.setText(QtGui.QApplication.translate("MainWindow", "&Empty frame", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCreate_new_frame.setShortcut(QtGui.QApplication.translate("MainWindow", "F", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "E&xit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_BLM.setText(QtGui.QApplication.translate("MainWindow", "&Load BLM", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_BLM.setToolTip(QtGui.QApplication.translate("MainWindow", "Load BML", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_BLM.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+L", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDuplicate_frame.setText(QtGui.QApplication.translate("MainWindow", "&Duplicate current frame", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDuplicate_frame.setShortcut(QtGui.QApplication.translate("MainWindow", "D", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlayStop.setText(QtGui.QApplication.translate("MainWindow", "&Play preview", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlayStop.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+P", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("MainWindow", "&New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_as.setText(QtGui.QApplication.translate("MainWindow", "&Save as...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_as.setIconText(QtGui.QApplication.translate("MainWindow", "Save as...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_as.setToolTip(QtGui.QApplication.translate("MainWindow", "Save as...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_as.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGo_to_previous_frame.setText(QtGui.QApplication.translate("MainWindow", "&Previous frame", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGo_to_previous_frame.setShortcut(QtGui.QApplication.translate("MainWindow", "P", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGo_to_next_frame.setText(QtGui.QApplication.translate("MainWindow", "&Next frame", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGo_to_next_frame.setShortcut(QtGui.QApplication.translate("MainWindow", "N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelect_all.setText(QtGui.QApplication.translate("MainWindow", "Select &all", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelect_all.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+A", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDeselect_all.setText(QtGui.QApplication.translate("MainWindow", "&Deselect all", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDeselect_all.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+A", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInvert_selection.setText(QtGui.QApplication.translate("MainWindow", "&Invert", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInvert_selection.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+I", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelect_by_color.setText(QtGui.QApplication.translate("MainWindow", "Select by &color", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelect_by_color.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+C", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUndo.setText(QtGui.QApplication.translate("MainWindow", "&Undo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUndo.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Z", None, QtGui.QApplication.UnicodeUTF8))
        self.actionChoose_color.setText(QtGui.QApplication.translate("MainWindow", "Choose &color", None, QtGui.QApplication.UnicodeUTF8))
        self.actionChoose_color.setShortcut(QtGui.QApplication.translate("MainWindow", "C", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTint_selected_tiles.setText(QtGui.QApplication.translate("MainWindow", "&Tint selected tiles", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTint_selected_tiles.setShortcut(QtGui.QApplication.translate("MainWindow", "T", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShift_left.setText(QtGui.QApplication.translate("MainWindow", "Left", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShift_left.setToolTip(QtGui.QApplication.translate("MainWindow", "Shift content left", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShift_left.setShortcut(QtGui.QApplication.translate("MainWindow", "Shift+Left", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShift_right.setText(QtGui.QApplication.translate("MainWindow", "Right", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShift_right.setShortcut(QtGui.QApplication.translate("MainWindow", "Shift+Right", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConnect_to_device.setText(QtGui.QApplication.translate("MainWindow", "Connect to device", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConnect_to_device.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+D", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlayStopDevice.setText(QtGui.QApplication.translate("MainWindow", "Play on device", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlayStopDevice.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Return", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRandomize_selected_tiles.setText(QtGui.QApplication.translate("MainWindow", "Randomize selected tiles", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRandomize_selected_tiles.setShortcut(QtGui.QApplication.translate("MainWindow", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShift_content_up.setText(QtGui.QApplication.translate("MainWindow", "Up", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShift_content_up.setShortcut(QtGui.QApplication.translate("MainWindow", "Shift+Up", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShift_content_down.setText(QtGui.QApplication.translate("MainWindow", "Down", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShift_content_down.setShortcut(QtGui.QApplication.translate("MainWindow", "Shift+Down", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy_Selection.setText(QtGui.QApplication.translate("MainWindow", "Copy colors", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy_Selection.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+C", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste.setText(QtGui.QApplication.translate("MainWindow", "Paste selection", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+V", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPersist_changes.setText(QtGui.QApplication.translate("MainWindow", "Persist changes", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPersist_changes.setShortcut(QtGui.QApplication.translate("MainWindow", "Return", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCut_Selection.setText(QtGui.QApplication.translate("MainWindow", "Cut colors", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCut_Selection.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+X", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExport_frame.setText(QtGui.QApplication.translate("MainWindow", "Export as image", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGenerate_color_gradient.setText(QtGui.QApplication.translate("MainWindow", "Color gradient", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGo_to_frame.setText(QtGui.QApplication.translate("MainWindow", "Enter frame...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGo_to_frame.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+F", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoom_in.setText(QtGui.QApplication.translate("MainWindow", "Zoom in", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoom_in.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+=", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoom_out.setText(QtGui.QApplication.translate("MainWindow", "Zoom out", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoom_out.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+-", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFit_zoom.setText(QtGui.QApplication.translate("MainWindow", "Fit zoom", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFit_zoom.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+0", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGenerate_function.setText(QtGui.QApplication.translate("MainWindow", "Function", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport_from_image.setText(QtGui.QApplication.translate("MainWindow", "Import from image", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRotate_right.setText(QtGui.QApplication.translate("MainWindow", "Rotate right", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRotate_right.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Right", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRotate_left.setText(QtGui.QApplication.translate("MainWindow", "Rotate left", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRotate_left.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Left", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDelete_colors.setText(QtGui.QApplication.translate("MainWindow", "D&elete colors", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDelete_colors.setShortcut(QtGui.QApplication.translate("MainWindow", "Del", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExport_frames.setText(QtGui.QApplication.translate("MainWindow", "Export frames", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDelete_frame.setText(QtGui.QApplication.translate("MainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDelete_frame.setShortcut(QtGui.QApplication.translate("MainWindow", "R", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGenerate_ticker_font.setText(QtGui.QApplication.translate("MainWindow", "Ticker text", None, QtGui.QApplication.UnicodeUTF8))

from gridgraphicsview import GridGraphicsView
import res_rc
